<?php
include_once 'gearweight.features.inc';

// function gearweight_menu(){
//   $items = array();
//   $items['gear_weight'] = array(
//     'title' => 'Calculate Gear Weight',
//     'type' => MENU_NORMAL_ITEM,
//     'access callback' => TRUE,
//     'page callback' => 'drupal_get_form',
//     'page arguments' => array('gearweight_form'),
//   );
//   $items['success'] = array(
//     'title' => 'Success',
//     'type' => MENU_CALLBACK,
//     'access callback' => TRUE,
//     'page callback' => 'sum_success',
//   );
//   return $items;
// }
//
// function gearweight_form(){
//   $form = array();
//   $form['left_number'] = array(
//     '#title' => 'Left Number',
//     '#type' => 'textfield',
//     '#description' => t('Please enter your starting number.'),
//   );
//   $form['right_number'] = array(
//     '#title' => 'Right Number',
//     '#type' => 'textfield',
//     '#description' => t('Please enter your finishing number.'),
//   );
//
//   $form['submit'] = array(
//     '#type' => 'submit',
//     '#value' => 'add it up',
//   );
//   return $form;
// }
//
// function gearweight_form_submit($form, &$form_state){
//   $first_number = $form_state['values']['left_number'];
//   $second_number = $form_state['values']['right_number'];
//   $sum = $first_number + $second_number;
//   $_SESSION['sum_output'] = $sum; //not specific name
//   $form_state['redirect'] = 'success';
// }
//
// function sum_success(){
//   $answer = $_SESSION['sum_output'];
//   return "you calculated a sum, it is $answer";
// }
