<?php
//pull in data from db.
function getWeights() {

$query = new EntityFieldQuery();

$query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'gear_post') //?
  ->propertyCondition('status', 1);

$result = $query->execute();

if (!empty($result['node'])) {
  $nids = array_keys($result['node']);
  $nodes = node_load_multiple($nids);
$weights = array();
  foreach ($nodes as $node) {
    // do something awesome);
     $fields = field_view_field('node', $node, 'field_weight'); //pull
    array_push ($weights, $fields[0]['#markup']); //push.
    }
}
//var_dump($weights);
return $weights;
}

function gweight_menu() {
    $items['gweight'] = array(
        'title' => 'Calculate Weight',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gweight_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['gweight_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'gweight_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function gweight_form() {
  $generate = getWeights();

  for ($i = 0; $i < count($generate); $i++){
    $form[$i] = array(
      '#title' => 'Item '.$i, //make this easier to read. This should come from db eventually.
      '#type' => 'textfield',
      '#default_value' => $generate[$i],
   );
  }

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function gweight_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['0'];
    $second_number = $form_state['values']['1'];
    $gweight = $first_number + $second_number;
    $_SESSION['gweight_output'] = $gweight;
    $form_state['redirect'] = 'gweight_success_page';
}

function gweight_success() {
    $answer = $_SESSION['gweight_output'];
    return 'You calculated a weight! The answer is: ' . $answer;
}
